# Generated by Django 5.2.17 on 2026-09-23 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('COMPUTER_LAB', 'Computer Lab'), ('LAB', 'Laboratory'), ('SEMINAR_HALL', 'Seminar Hall')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='academics.department')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('building', 'room_number'), name='unique_room')],
            },
        ),
    ]
