# Generated by Django 5.2.17 on 2026-09-23 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject'),
        ('account', '0002_remove_user_full_name_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='academics.department'),
        ),
    ]
