# Generated by Django 5.2.17 on 2026-09-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
