# Generated by Django 5.2.17 on 2026-09-23 08:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_teacher_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='profile_picture'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='profile_picture'),
        ),
    ]
