# Generated by Django 5.2.17 on 2026-09-24 13:26

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_teachers'),
        ('account', '0010_alter_student_student_id_alter_teacher_employee_id'),
        ('rooms', '0001_initial'),
        ('scheduling', '0002_enable_btree_gist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'SCHEDULED'), ('time_range__isnull', False)), expressions=[('teacher', '='), ('time_range', '&&')], name='no_teacher_time_overlap'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'SCHEDULED'), ('time_range__isnull', False)), expressions=[('batch', '='), ('time_range', '&&')], name='no_batch_time_overlap'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'SCHEDULED'), ('time_range__isnull', False)), expressions=[('room', '='), ('time_range', '&&')], name='no_room_time_overlap'),
        ),
    ]
