# Generated by Django 5.2.17 on 2026-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_classsession_time_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLASS_CREATED', 'Class Created'), ('CLASS_RESCHEDULED', 'Class Rescheduled'), ('CLASS_CANCELLED', 'Class Cancelled')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
