# Generated by Django 5.2.17 on 2026-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject'),
        ('account', '0007_student_profile_picture_teacher_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='account.teacher'),
        ),
    ]
